### ISSUE TITLE
Mongodb adapter cannot synchronize with other server nodes

### ISSUE THREAD

**Issue by tmotagam** [socketio/socket.io-mongo-adapter#11]
Hi,
When I use _FetchSockets_ function to fetch sockets from other servers the function returns only local socket and no remote sockets which is false, on digging deeper the _nodesMap_ which keeps all the nodes data gives different data in _FetchSockets_ function and in _onEvent_ function.
In _onevent_ function the _nodesMap_ says there is one node present/active (which is true I only have one other server active for testing) and in the _FetchSockets_ it says zero node is active/present.

_nodejs:  18.x ,
os: windows,
mongodb: 5.x (atlas),
socket.io: 4.5.4,
mongo-adapter: 0.2.1_

**Comment by darrachequesne** [comment]
Hi! I was not able to reproduce the issue: https://github.com/socketio/socket.io-fiddle/tree/socket.io-mongo-adapter/issues/11

Could you please check?

**Comment by tmotagam** [comment]
Hi @darrachequesne,
 Yes I have done my investigation and there is no issue there is a synchronization delay between two servers for any newly created nsp which i was creating dynamically and thinking that there is only one instance of adapter but after your fiddle I started digging again to find that there is addition of new adapters for every new nsp created on the two servers and then after that there is synchronization between the two which I was not waiting for. So the issue is resolved, just one question why new adapters for every nsp is that so multiplexing can be done ?
 Thanks again for helping me.

**Comment by darrachequesne** [comment]
> why new adapters for every nsp is that so multiplexing can be done ?

Hmm, good question! That's how it was implemented, there is one adapter per namespace (but one single change stream for all namespaces, see https://github.com/socketio/socket.io-mongo-adapter/commit/9b5f4c83038cc212b898b7fb7ff0ccec3124447c) and indeed an [heartbeat mechanism](https://github.com/socketio/socket.io-mongo-adapter/blob/a5d000fc665015f0bbf7c7ad4e918403eb7904fc/lib/index.ts#L222-L224) between namespaces on different Socket.IO servers, which is used to know the number of nodes in the cluster.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
