### ISSUE TITLE
Feature Request: Add createdAt timestamp in documents

### ISSUE THREAD

**Issue by manishmotiani** [socketio/socket.io-mongo-adapter#2]
Feature Request: Add createdAt timestamp in documents

This fields will help in keeping collection clean with TTL index on createdAt.
createdAt can be option and set only if set in MongoAdapterOptions

**Comment by SebassCoates** [comment]
@manishmotiani I came here looking for the same feature, but I just learned that [capped collections don't support TTL indices](https://www.mongodb.com/docs/manual/core/index-ttl/#:~:text=The%20_id%20field%20does%20not,documents%20from%20a%20capped%20collection).  It seems like the performance advantage of capped collections is pretty integral to this library, so it might not be possible to make this change.

**Comment by darrachequesne** [comment]
@manishmotiani hi! Could you please explain your use case?

If I recall correctly, capped collections are more efficient than TTL indexes in that case, but I don't mind adding an option to cover both use cases.

See also: https://stackoverflow.com/questions/34181516/mongo-ttl-vs-capped-collections-for-efficiency

**Comment by manishmotiani** [comment]
@darrachequesne socket data in mongodb is useful for say 6 hours. To keep things clean, I want it to auto remove document based on TTL which work on date/timestamp field index.

what should ideal size for capped collection if we don't want to use too much or too less space?

**Comment by darrachequesne** [comment]
@manishmotiani well, that's the tricky part, since it depends on your own usage:

- how many Socket.IO servers?
- how many broadcast per second?
- how big each packet is?

I'd say you only need a few minutes of historic data, to handle temporary disconnections to the MongoDB cluster. Having both a max size (`size` option) and a max number of documents (`max` option) might help a bit.

Reference: https://www.mongodb.com/docs/manual/core/capped-collections/#create-a-capped-collection

**Comment by manishmotiani** [comment]
@darrachequesne Thanks this helps. Currently there is not much server load and packet size is few kbs. Limiting with max number of document will help achieve the purpose.

Now only use case for adding timestamp is for analytics to generate how many messages going through in a specific time period across all or specific server.

If you think that is good use case, then we can proceed with this enhancement or probably add in future timeline.

**Comment by manishmotiani** [comment]
Thanks
