### ISSUE TITLE
serverCount function doesn't exclude offline nodes

### ISSUE THREAD

**Issue by OverSamu** [socketio/socket.io-mongo-adapter#22]
Hi, I'm having a problem with SocketIO and so I looked at the code of this adapter, in use in my project.
I'm wondering if the serverCount() function shouldn't perform the checks that the getExpectedResponseCount() function does, as it currently seems to return the number of nodes without excluding the offline ones.
https://github.com/socketio/socket.io-mongo-adapter/blob/57a6dfbe45df4d74a60867e1c11e8c3f15d13522/lib/index.ts#L619-L621
https://github.com/socketio/socket.io-mongo-adapter/blob/57a6dfbe45df4d74a60867e1c11e8c3f15d13522/lib/index.ts#L674-L683

I'm analyzing these behaviors since when I send broadcast messages with callbacks, after a node is no longer reachable I get a timeout despite all online sockets having sent their response.
I noticed that [emit](https://github.com/socketio/socket.io/blob/e36062ca2df0b1a4adcf986bafc3fd92675d3896/lib/broadcast-operator.ts#L282) uses serverCount(), and this could be the cause.

As a workaround I'm calling the [fetchSockets()](https://github.com/socketio/socket.io/blob/e36062ca2df0b1a4adcf986bafc3fd92675d3896/lib/broadcast-operator.ts#L359) function before each emit, which in the adapter [uses](https://github.com/socketio/socket.io-mongo-adapter/blob/57a6dfbe45df4d74a60867e1c11e8c3f15d13522/lib/index.ts#L687C40-L687C64) the getExpectedResponseCount() function that updates the node map by removing the offline ones.

Can you let me know something about it?
Thank you

**Comment by darrachequesne** [comment]
You are right, `serverCount()` does not currently exclude offline nodes.

This should be fixed by https://github.com/socketio/socket.io-mongo-adapter/pull/23, could you please check?

**Comment by OverSamu** [comment]
Hi, your PR solves this problem.
I will wait for the new release.

Thank you
