### ISSUE TITLE
Cleaning up empty namespaces

### ISSUE THREAD

**Issue by rchadwic** [socketio/socket.io-mongo-adapter#3]
I wonder if anyone could offer any advice here:

My application creates namespaces dynamically. The load on the database server steadily increases as more and more change streams are opened, one per node per namespace. After a few days, the majority of the DB capacity is spent servicing change streams for namespaces that no one is listening to. 

I've attempted to clean up manually, with the code below. This appears to cause errors, as some nodes believe the namespaces exists while others do not.  How can I close out the change streams and destroy the namespace properly, and how would I know when that is?

```
 function clearEmptyNamespaces() {
            for (const nsp of io._nsps) {
                if (nsp[0] !== '/' && nsp[0] !== '/launch' && nsp[0] !== '/system' && nsp[0] !== '/admin') {
                    const namespace = nsp[1];
                    if (namespace.sockets.size == 0) {
                        console.log('Removing namespace' + nsp[0]);
                        io._nsps.delete(nsp);
                        namespace.adapter.close();
                    }
                }
            }
        }
```

**Comment by darrachequesne** [comment]
You are right, the current implementation is not well suited for dynamic namespaces. I think that we could instead have a single change stream, which sends each change to the right adapter.

In you example, `namespace.adapter.close()` should indeed close the change stream, but it does not notify the other nodes ([here](https://github.com/socketio/socket.io-mongo-adapter/blob/cec123a03f8c5d847eeaf5cb52f079b5f372b48a/lib/index.ts#L146-L154)), so there might be some errors during the `heartbeatTimeout` delay.

**Comment by rchadwic** [comment]
I had no trouble replacing the call to collection.watch with a global singleton changestream, and doing the little bit of matching logic in Node instead of Mongo. I can't really think of any downsides to this approach, but I'll run it in production for a while and see.

**Comment by rchadwic** [comment]
That seemed to make a huge difference! Check out how the load on the DB plummets. Are there any downsides here? I guess a small amount of compute is transferred to Node (evaluating if the namespace == this.nsp and uid !== this.uid)

![image](https://user-images.githubusercontent.com/1257870/162211790-9f6b25f2-a975-4773-8ebd-e0163d928662.png)

**Comment by darrachequesne** [comment]
Awesome, thanks for the update!

I don't think there are any security implications. Would you have time to open a pull request with your changes?

**Comment by darrachequesne** [comment]
Implemented in https://github.com/socketio/socket.io-mongo-adapter/commit/9b5f4c83038cc212b898b7fb7ff0ccec3124447c, and included in `@socket.io/mongo-adapter@0.2.0`. Thanks!
