### ISSUE TITLE
why ? Error: Cannot install  '@socket.io/mongo-adapter'

### ISSUE THREAD

**Issue by AbbasAlsbihawi** [socketio/socket.io-mongo-adapter#6]
Error: Cannot install  '@socket.io/mongo-adapter'

npm install @socket.io/mongo-adapter mongodb
At line:1 char:13
+ npm install @socket.io/mongo-adapter mongodb
+             ~~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@socket' can be used only as an
argument to a command. To reference variables in an expression use '$socket'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted

**Comment by darrachequesne** [comment]
Hi! Did you try with quotes:

```
npm install "@socket.io/mongo-adapter" mongodb
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
