### ISSUE TITLE
Question: capped collection or TTL?

### ISSUE THREAD

**Issue by tudor33sud** [socketio/socket.io-mongo-adapter#7]
Hello,

First of all, thanks for the awesome integration with MongoDB for making devs life easier! 

I am just starting using the adapter in our mongodb workloads + socketIO, and I am not sure how capped collection / TTL collection are matching up to each other. I started off by using a capped collection as shown in the example by having 1e6 ( 1mb ) capped collection and everything seems to be working fine.

From what I've read in mongodb docs, capped collections tend to have a better write performance, thus I kind of incline thinking about a capped collection instead of ttl one. Were there any performance benchmarks done on these 2 approaches? Is there any advice on which one should be used? As far as I've seen, ttl collections were newly introduced in 0.2 version of the adapter, so I'm wondering whether that's better and why.

We are using socket io for a chat application + live notifications (achievements, in app notifications etc.). I would love hearing from you so that I know I could make up my mind correctly. Thanks in advance!

**Comment by tudor33sud** [comment]
@darrachequesne  if you get a chance, I would be greatful to hear your take on this one, since I see you are the one maintaining these repos. We are somehow in the process of releasing, I would be happy if I could hear your thoughts before. (for the first iteration, I went with a capped collection of 10mb )

**Comment by darrachequesne** [comment]
@tudor33sud hi! The reasoning for the TTL collections is explained here: https://github.com/socketio/socket.io-mongo-adapter/issues/2#issuecomment-1091074496

> Now only use case for adding timestamp is for analytics to generate how many messages going through in a specific time period across all or specific server.

I'd say that, by default, one should use a capped collection, since it should indeed have a better write performance.

**Comment by tudor33sud** [comment]
I see now! That totally makes sense! I guess we'll stick with capped collection as a personal decision for now! Thanks a lot for your assistance!
